### ISSUE TITLE
Admin clicks on ‘New Cohort’ ->

### ISSUE THREAD

**Issue by MrAaronOlsen** [turingschool/full-circle#19]
- They will be shown a form allowing them to create an ‘Open Application Window’.
- An ‘Open Application Window’ will have a start date and an end date.
- An ‘Open Application Window’ will have a cohort number.

**Comment by VictoriaVasys** [comment]
• Title
• Start Date
• End Date
• Open Date
• Close Date
• Notify Date

**Comment by VictoriaVasys** [comment]
The button doesn't open a new window, just pops up an instance of a cohort (and changes first current cohort attm)

**Comment by VictoriaVasys** [comment]
Closing because this will now be managed through Census (see #132)
