### ISSUE TITLE
Admin clicks on any application

### ISSUE THREAD

**Issue by MrAaronOlsen** [turingschool/full-circle#21]
- They will be shown the essay and all total scores for that application.
- Each criteria will be averaged across all reviews.
- A list of each review with criteria scores will be shown to the side.
- Admins will have access to Name and Email of student.
- An admin can not edit any scores submitted by a reviewer.

**Comment by VictoriaVasys** [comment]
* Not sure how best to show each review; for now it will be total for each criteria & total for all totals
* Also order applications on the left based on score?

**Comment by VictoriaVasys** [comment]
* We should also display the application id # since that's the only info the reviewer gets, in case they have an issue
